version: '3'

services:
  client:
    build:
      context: .
    container_name: client
    depends_on:
      - eth-node
    networks:
      - eth-network
    volumes:
      - ./contracts:/app/contracts 
      - ./deployers:/app/deployers 
      - ./clients:/app/clients 
      - ./package.json:/app/package.json 


  eth-node:
    image: ethereum/client-go:stable
    container_name: eth-node
    networks:
      - eth-network
    ports:
      - "8545:8545" 
    command:
      [
        "--dev",                 
        "--http",                
        "--http.addr", "0.0.0.0", 
        "--http.port", "8545",    
        "--http.api", "personal,web3,eth,net,admin,debug", 
        "--allow-insecure-unlock",    
        "--http.corsdomain", "*",
        "--http.vhosts", "*",
      ]

networks:
  eth-network:
    driver: bridge
